import retroSound from "../../assets/sounds/retro.wav";
import twinkleSound from "../../assets/sounds/twinkle.mp3";
import answerSound from "../../assets/sounds/answer.mp3";
import archiveSound from "../../assets/sounds/archive.mp3";
import clickSound from "../../assets/sounds/click.mp3";
import exciteSound from "../../assets/sounds/excite.mp3";
import shallowSound from "../../assets/sounds/shallow.mp3";
import notifySound from "../../assets/sounds/notify.mp3";
import pingSound from "../../assets/sounds/ping.mp3";
import popSound from "../../assets/sounds/pop.mp3";
import progressSound from "../../assets/sounds/progress.mp3";
import purchaseSound from "../../assets/sounds/purchase.mp3";
import successSound from "../../assets/sounds/success.mp3";
import tapSound from "../../assets/sounds/tap.mp3";
import tuckSound from "../../assets/sounds/tuck.mp3";
export const useSound = (value) => {
  const retro = new Audio(retroSound);
  const twinkle = new Audio(twinkleSound);
  const answer = new Audio(answerSound);
  const archive = new Audio(archiveSound);
  const click = new Audio(clickSound);
  const excite = new Audio(exciteSound);
  const shallow = new Audio(shallowSound);
  const notify = new Audio(notifySound);
  const ping = new Audio(pingSound);
  const pop = new Audio(popSound);
  const progress = new Audio(progressSound);
  const success = new Audio(successSound);
  const tap = new Audio(tapSound);
  const tuck = new Audio(tuckSound);
  const purchase = new Audio(purchaseSound);

  if (value == "Retro") return retro;
  if (value == "Twinkle") return twinkle;
  if (value == "Answer") return answer;
  if (value == "Archive") return archive;
  if (value == "Click") return click;
  if (value == "Excite") return excite;
  if (value == "Shallow") return shallow;
  if (value == "Notify") return notify;
  if (value == "Ping") return ping;
  if (value == "Pop") return pop;
  if (value == "Progress") return progress;
  if (value == "Success") return success;
  if (value == "Tap") return tap;
  if (value == "Tuck") return tuck;
  if (value == "Purchase") return purchase;
};
